dataset: rotcifar10hardmax10c
model_type: resnet18
num_centers: 40
epochs: 10
local_epochs: 10
batch_size: 64
optimizer: SGD
lr: 1.0e-2
num_workers: 4
device: 0
out_dir: runs_cifar
seed: 0
save_every: 50

# threshold for other methods
threshold: 0.5

# tolerance and projection ratio for emd-cfl
tolerance: 0.1
proj_ratio: 0.9

# for methods requiring num_clusters: IFCA, CFLGP, FedSoft, FedEM, FlexCFL, FedRC
num_clusters: 1

# proximal loss for: FedProx, pFedGraph, FedSaC, FeSEM - these have been hardcoded in each runner
mu: 0